controller_list:
  - name: position_trajectory_controller
    action_ns: follow_joint_trajectory
    type: position_controllers/JointTrajectoryController
    default: true
    joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
